name: konekto_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  table_calendar: ^3.0.0
  intl: ^0.20.2
  dotted_border: ^2.1.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter: # Esta linha alinhada à esquerda
  uses-material-design: true # Esta linha indentada com dois espaços
  
  assets: # Esta linha indentada com dois espaços
    - assets/themes/konekto_app_theme.json
    - assets/images/konekto_logo.png # Logo Konekto (fixa, fora das pastas de tenant)
    - assets/images/placeholder.png  # Imagens de fallback genéricas
    
    # Inclusão genérica da pasta raiz de tenants (para pegar JSONs na raiz de cada tenant, por exemplo)
    - assets/tenants/ # Esta linha indentada com quatro espaços
    
    # INCLUSÃO EXPLÍCITA DE CADA PASTA DE TENANT (RECOMENDADO PARA ROBUSTEZ)
    # Isso garante que TODO o conteúdo de cada pasta de tenant seja incluído.
    # Esta é a parte que você provavelmente sentiu falta.
    
    - assets/tenants/konekto_app/ # Inclui tudo dentro de konekto_app/
    - assets/tenants/beach_park/  # Inclui tudo dentro de beach_park/
    - assets/tenants/copacabana_palace/ # Inclui tudo dentro de copacabana_palace/

    # Além disso, para maior clareza e como uma camada extra de segurança, 
    # listamos as subpastas de imagens mais comuns DENTRO DE CADA TENANT.
    # Embora as linhas acima teoricamente já incluam isso, ser explícito pode evitar problemas.
    # Mantenha a indentação de 4 espaços.

    # konekto configs
    # Ad Banners - Tenants
    - assets/images/ad_banners/ad_horizontal_1.png
    - assets/images/ad_banners/ad_horizontal_2.png
    - assets/images/ad_banners/ad_horizontal_3.png

    # Banner konekto
    - assets/images/banner/konekto_banner.png
    
    # json konekto
    - assets/config/ad_banners.json
    - assets/themes/konekto_app_theme.json




    # Para konekto_app:
    - assets/tenants/konekto_app/images/

    - assets/tenants/konekto_app/images/banners/banner1.png
    - assets/tenants/konekto_app/images/banners/banner2.png
    - assets/tenants/konekto_app/images/banners/pool_background.png
    - assets/tenants/konekto_app/images/banners/reservas_banner.jpg
    - assets/tenants/konekto_app/images/banners/room_service_banner.jpg
    - assets/tenants/konekto_app/images/banners/services_background.png

    - assets/tenants/konekto_app/images/cardapio/arroz_biro_biro.jpg
    - assets/tenants/konekto_app/images/cardapio/bife_ancho.jpg
    - assets/tenants/konekto_app/images/cardapio/bruschetta.jpg
    - assets/tenants/konekto_app/images/cardapio/bruschetta.jpg
    - assets/tenants/konekto_app/images/cardapio/cabernet.jpg
    - assets/tenants/konekto_app/images/cardapio/caprese.jpg
    - assets/tenants/konekto_app/images/cardapio/cerveja_japonesa.jpg
    - assets/tenants/konekto_app/images/cardapio/chateau_margaux.jpg
    - assets/tenants/konekto_app/images/cardapio/combinado.jpg
    - assets/tenants/konekto_app/images/cardapio/farofa.jpg
    - assets/tenants/konekto_app/images/cardapio/file_mignon.jpg
    - assets/tenants/konekto_app/images/cardapio/guioza.jpg
    - assets/tenants/konekto_app/images/cardapio/malbec.jpg
    - assets/tenants/konekto_app/images/cardapio/picanha.jpg
    - assets/tenants/konekto_app/images/cardapio/risoto.jpg
    - assets/tenants/konekto_app/images/cardapio/sake.jpg
    - assets/tenants/konekto_app/images/cardapio/sauvignon_blanc.jpg
    - assets/tenants/konekto_app/images/cardapio/sunomono.jpg
    - assets/tenants/konekto_app/images/cardapio/temaki.jpg


    - assets/tenants/konekto_app/images/cardapio/room_services/agua.jpg
    - assets/tenants/konekto_app/images/cardapio/room_services/batata.jpg
    - assets/tenants/konekto_app/images/cardapio/room_services/cafe.jpg
    - assets/tenants/konekto_app/images/cardapio/room_services/cerveja.jpg
    - assets/tenants/konekto_app/images/cardapio/room_services/iogurte.jpg
    - assets/tenants/konekto_app/images/cardapio/room_services/omelete.jpg
    - assets/tenants/konekto_app/images/cardapio/room_services/pães.jpg
    - assets/tenants/konekto_app/images/cardapio/room_services/queijos.jpg
    - assets/tenants/konekto_app/images/cardapio/room_services/sanduiche.jpg
    - assets/tenants/konekto_app/images/cardapio/room_services/suco.jpg

    - assets/tenants/konekto_app/images/restaurantes/hanabi_sushi.png
    - assets/tenants/konekto_app/images/restaurantes/le_mare.png
    - assets/tenants/konekto_app/images/restaurantes/toro_brasa.png

    - assets/tenants/konekto_app/images/spa/limpeza_de_pele.png
    - assets/tenants/konekto_app/images/spa/massagem_relaxante.png
    - assets/tenants/konekto_app/images/spa/massagem_terapeutica.png
    - assets/tenants/konekto_app/images/spa/spa_background.png
    - assets/tenants/konekto_app/images/spa/tratamento_antiidade.png


    - assets/tenants/konekto_app/images/eventos/eventos1.jpg

    - assets/tenants/konekto_app/images/mapa/mapa_do_hotel.png
    - assets/tenants/konekto_app/images/mapa/mapa1.jpg

    - assets/tenants/konekto_app/images/passeios/passeios1.jpg

    
    - assets/tenants/konekto_app/images/logos/default_logo.png
    
    # Para beach_park:
    - assets/tenants/beach_park/images/
    - assets/tenants/beach_park/images/banners/banner1.png
    - assets/tenants/beach_park/images/banners/banner2.png
    - assets/tenants/beach_park/images/banners/pool_background.png
    - assets/tenants/beach_park/images/banners/reservas_banner.jpg
    - assets/tenants/beach_park/images/banners/room_service_banner.jpg
    - assets/tenants/beach_park/images/banners/services_background.png

    - assets/tenants/beach_park/images/cardapio/arroz_biro_biro.jpg
    - assets/tenants/beach_park/images/cardapio/bife_ancho.jpg
    - assets/tenants/beach_park/images/cardapio/bruschetta.jpg
    - assets/tenants/beach_park/images/cardapio/bruschetta.jpg
    - assets/tenants/beach_park/images/cardapio/cabernet.jpg
    - assets/tenants/beach_park/images/cardapio/caprese.jpg
    - assets/tenants/beach_park/images/cardapio/cerveja_japonesa.jpg
    - assets/tenants/beach_park/images/cardapio/chateau_margaux.jpg
    - assets/tenants/beach_park/images/cardapio/combinado.jpg
    - assets/tenants/beach_park/images/cardapio/farofa.jpg
    - assets/tenants/beach_park/images/cardapio/file_mignon.jpg
    - assets/tenants/beach_park/images/cardapio/guioza.jpg
    - assets/tenants/beach_park/images/cardapio/malbec.jpg
    - assets/tenants/beach_park/images/cardapio/picanha.jpg
    - assets/tenants/beach_park/images/cardapio/risoto.jpg
    - assets/tenants/beach_park/images/cardapio/sake.jpg
    - assets/tenants/beach_park/images/cardapio/sauvignon_blanc.jpg
    - assets/tenants/beach_park/images/cardapio/sunomono.jpg
    - assets/tenants/beach_park/images/cardapio/temaki.jpg


    - assets/tenants/beach_park/images/cardapio/room_services/agua.jpg
    - assets/tenants/beach_park/images/cardapio/room_services/batata.jpg
    - assets/tenants/beach_park/images/cardapio/room_services/cafe.jpg
    - assets/tenants/beach_park/images/cardapio/room_services/cerveja.jpg
    - assets/tenants/beach_park/images/cardapio/room_services/iogurte.jpg
    - assets/tenants/beach_park/images/cardapio/room_services/omelete.jpg
    - assets/tenants/beach_park/images/cardapio/room_services/pães.jpg
    - assets/tenants/beach_park/images/cardapio/room_services/queijos.jpg
    - assets/tenants/beach_park/images/cardapio/room_services/sanduiche.jpg
    - assets/tenants/beach_park/images/cardapio/room_services/suco.jpg

    - assets/tenants/beach_park/images/restaurantes/hanabi_sushi.png
    - assets/tenants/beach_park/images/restaurantes/le_mare.png
    - assets/tenants/beach_park/images/restaurantes/toro_brasa.png

    - assets/tenants/beach_park/images/spa/limpeza_de_pele.png
    - assets/tenants/beach_park/images/spa/massagem_relaxante.png
    - assets/tenants/beach_park/images/spa/massagem_terapeutica.png
    - assets/tenants/beach_park/images/spa/spa_background.png
    - assets/tenants/beach_park/images/spa/tratamento_antiidade.png


    - assets/tenants/beach_park/images/eventos/eventos1.jpg

    - assets/tenants/beach_park/images/mapa/mapa_do_hotel.png
    - assets/tenants/beach_park/images/mapa/mapa1.jpg

    - assets/tenants/beach_park/images/passeios/passeios1.jpg

    
    - assets/tenants/beach_park/images/logos/beach_park_logo.png
    
    # Para copacabana_palace:
    - assets/tenants/copacabana_palace/images/
    - assets/tenants/copacabana_palace/images/banners/banner1.png
    - assets/tenants/copacabana_palace/images/banners/banner2.png
    - assets/tenants/copacabana_palace/images/banners/pool_background.png
    - assets/tenants/copacabana_palace/images/banners/reservas_banner.jpg
    - assets/tenants/copacabana_palace/images/banners/room_service_banner.jpg
    - assets/tenants/copacabana_palace/images/banners/services_background.png

    - assets/tenants/copacabana_palace/images/cardapio/arroz_biro_biro.jpg
    - assets/tenants/copacabana_palace/images/cardapio/bife_ancho.jpg
    - assets/tenants/copacabana_palace/images/cardapio/bruschetta.jpg
    - assets/tenants/copacabana_palace/images/cardapio/bruschetta.jpg
    - assets/tenants/copacabana_palace/images/cardapio/cabernet.jpg
    - assets/tenants/copacabana_palace/images/cardapio/caprese.jpg
    - assets/tenants/copacabana_palace/images/cardapio/cerveja_japonesa.jpg
    - assets/tenants/copacabana_palace/images/cardapio/chateau_margaux.jpg
    - assets/tenants/copacabana_palace/images/cardapio/combinado.jpg
    - assets/tenants/copacabana_palace/images/cardapio/farofa.jpg
    - assets/tenants/copacabana_palace/images/cardapio/file_mignon.jpg
    - assets/tenants/copacabana_palace/images/cardapio/guioza.jpg
    - assets/tenants/copacabana_palace/images/cardapio/malbec.jpg
    - assets/tenants/copacabana_palace/images/cardapio/picanha.jpg
    - assets/tenants/copacabana_palace/images/cardapio/risoto.jpg
    - assets/tenants/copacabana_palace/images/cardapio/sake.jpg
    - assets/tenants/copacabana_palace/images/cardapio/sauvignon_blanc.jpg
    - assets/tenants/copacabana_palace/images/cardapio/sunomono.jpg
    - assets/tenants/copacabana_palace/images/cardapio/temaki.jpg


    - assets/tenants/copacabana_palace/images/cardapio/room_services/agua.jpg
    - assets/tenants/copacabana_palace/images/cardapio/room_services/batata.jpg
    - assets/tenants/copacabana_palace/images/cardapio/room_services/cafe.jpg
    - assets/tenants/copacabana_palace/images/cardapio/room_services/cerveja.jpg
    - assets/tenants/copacabana_palace/images/cardapio/room_services/iogurte.jpg
    - assets/tenants/copacabana_palace/images/cardapio/room_services/omelete.jpg
    - assets/tenants/copacabana_palace/images/cardapio/room_services/pães.jpg
    - assets/tenants/copacabana_palace/images/cardapio/room_services/queijos.jpg
    - assets/tenants/copacabana_palace/images/cardapio/room_services/sanduiche.jpg
    - assets/tenants/copacabana_palace/images/cardapio/room_services/suco.jpg

    - assets/tenants/copacabana_palace/images/restaurantes/hanabi_sushi.png
    - assets/tenants/copacabana_palace/images/restaurantes/le_mare.png
    - assets/tenants/copacabana_palace/images/restaurantes/toro_brasa.png

    - assets/tenants/copacabana_palace/images/spa/limpeza_de_pele.png
    - assets/tenants/copacabana_palace/images/spa/massagem_relaxante.png
    - assets/tenants/copacabana_palace/images/spa/massagem_terapeutica.png
    - assets/tenants/copacabana_palace/images/spa/spa_background.png
    - assets/tenants/copacabana_palace/images/spa/tratamento_antiidade.png


    - assets/tenants/copacabana_palace/images/eventos/eventos1.jpg

    - assets/tenants/copacabana_palace/images/mapa/mapa_do_hotel.png
    - assets/tenants/copacabana_palace/images/mapa/mapa1.jpg

    - assets/tenants/copacabana_palace/images/passeios/passeios1.jpg

    
    - assets/tenants/copacabana_palace/images/logos/copacabana_logo.png
    
    # Se você adicionar mais tenants no futuro, lembre-se de adicionar suas pastas raiz e de imagens aqui!