import { NextRequest, NextResponse } from 'next/server'
import { z } from 'zod'
import type { Prisma } from '@/app/generated/prisma/client'
import { prisma } from '@/lib/prisma'
import { requireStaffRole, AuthGuardError } from '@/lib/auth-guard'
import { verifyStaffToken } from '@/lib/jwt'
import { autoTranslateOrNull } from '@/lib/translate'
import { validateOperatingHoursFields } from '@/lib/scheduling'
import { resolveHotelEnabledModuleIds } from '@/lib/service-module-gate'

export const runtime = 'nodejs'

async function isGerenteOfHotel(request: NextRequest, hotelId: string): Promise<boolean> {
  const authHeader = request.headers.get('authorization')
  const token = authHeader?.startsWith('Bearer ') ? authHeader.slice(7) : null
  if (!token) return false
  try {
    const payload = await verifyStaffToken(token)
    return payload.role === 'gerente' && payload.hotelId === hotelId
  } catch {
    return false
  }
}

export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ hotelId: string; serviceId: string }> },
) {
  const { hotelId, serviceId } = await params
  const service = await prisma.service.findUnique({
    where: { id: serviceId, hotelId },
    include: { items: { where: { hidden: false }, orderBy: { position: 'asc' } }, tableTypes: true },
  })
  if (!service) {
    return NextResponse.json({ error: 'service_not_found' }, { status: 404 })
  }
  const isGerente = await isGerenteOfHotel(request, hotelId)
  if (!service.enabled && !isGerente) {
    return NextResponse.json({ error: 'service_not_found' }, { status: 404 })
  }
  if (!isGerente && service.moduleId != null) {
    const enabledModuleIds = await resolveHotelEnabledModuleIds(hotelId)
    if (!enabledModuleIds.has(service.moduleId)) {
      return NextResponse.json({ error: 'service_not_found' }, { status: 404 })
    }
  }
  return NextResponse.json(service)
}

const translationFieldsSchema = z.object({
  en: z.record(z.string(), z.string()).optional(),
  es: z.record(z.string(), z.string()).optional(),
})

const patchServiceSchema = z.object({
  name: z.string().min(1).optional(),
  icon: z.string().min(1).optional(),
  description: z.string().optional(),
  // `category` é só organização visual — pode mudar depois. `type`
  // (comportamento) não está aqui de propósito: uma vez criado, não muda.
  category: z.string().trim().min(1).optional(),
  bannerImageUrl: z.string().min(1).nullable().optional(),
  enabled: z.boolean().optional(),
  position: z.number().int().min(0).optional(),
  operatingDaysOfWeek: z.array(z.number().int().min(1).max(7)).optional(),
  operatingStartMinute: z.number().int().min(0).max(1439).nullable().optional(),
  operatingEndMinute: z.number().int().min(0).max(1439).nullable().optional(),
  // Presença desta chave = edição manual de tradução feita no portal —
  // desliga a tradução automática futura desse serviço (ver
  // `translationsAutoGenerated` no schema), pra não sobrescrever a edição
  // manual na próxima vez que `name`/`description` mudar.
  translations: translationFieldsSchema.optional(),
})

async function authorizeGerente(request: NextRequest, hotelId: string): Promise<NextResponse | null> {
  try {
    const staff = await requireStaffRole(request, ['gerente'])
    if (staff.hotelId !== hotelId) {
      return NextResponse.json({ error: 'forbidden' }, { status: 403 })
    }
  } catch (error) {
    if (error instanceof AuthGuardError) return error.response
    throw error
  }
  return null
}

export async function PATCH(
  request: NextRequest,
  { params }: { params: Promise<{ hotelId: string; serviceId: string }> },
) {
  const { hotelId, serviceId } = await params

  const authError = await authorizeGerente(request, hotelId)
  if (authError) return authError

  const parsed = patchServiceSchema.safeParse(await request.json().catch(() => null))
  if (!parsed.success) {
    return NextResponse.json({ error: 'invalid_request' }, { status: 400 })
  }

  const existing = await prisma.service.findUnique({ where: { id: serviceId, hotelId } })
  if (!existing) {
    return NextResponse.json({ error: 'service_not_found' }, { status: 404 })
  }

  // PATCH é parcial — precisa validar o horário de funcionamento resultante
  // (existente + o que veio no body), não só os campos que o body trouxe,
  // mesmo racional já usado no PATCH de `ServiceItem`.
  const operatingHoursCheck = validateOperatingHoursFields({
    operatingDaysOfWeek: parsed.data.operatingDaysOfWeek !== undefined ? parsed.data.operatingDaysOfWeek : existing.operatingDaysOfWeek,
    operatingStartMinute:
      parsed.data.operatingStartMinute !== undefined ? parsed.data.operatingStartMinute : existing.operatingStartMinute,
    operatingEndMinute:
      parsed.data.operatingEndMinute !== undefined ? parsed.data.operatingEndMinute : existing.operatingEndMinute,
  })
  if (!operatingHoursCheck.ok) {
    return NextResponse.json({ error: operatingHoursCheck.error }, { status: 400 })
  }

  const { translations: manualTranslations, ...rest } = parsed.data
  const updateData: Prisma.ServiceUpdateInput = { ...rest }

  if (manualTranslations) {
    updateData.translations = manualTranslations as Prisma.InputJsonValue
    updateData.translationsAutoGenerated = false
  } else if ((parsed.data.name !== undefined || parsed.data.description !== undefined) && existing.translationsAutoGenerated) {
    const autoTranslations = await autoTranslateOrNull({
      name: parsed.data.name ?? existing.name,
      description: parsed.data.description ?? existing.description,
    })
    if (autoTranslations) {
      updateData.translations = autoTranslations as Prisma.InputJsonValue
    }
  }

  const updated = await prisma.service.update({
    where: { id: serviceId },
    data: updateData,
  })
  return NextResponse.json(updated)
}

export async function DELETE(
  request: NextRequest,
  { params }: { params: Promise<{ hotelId: string; serviceId: string }> },
) {
  const { hotelId, serviceId } = await params

  const authError = await authorizeGerente(request, hotelId)
  if (authError) return authError

  const existing = await prisma.service.findUnique({ where: { id: serviceId, hotelId } })
  if (!existing) {
    return NextResponse.json({ error: 'service_not_found' }, { status: 404 })
  }

  await prisma.service.delete({ where: { id: serviceId } })
  return NextResponse.json({ success: true })
}
