import { NextRequest, NextResponse } from 'next/server'
import { z } from 'zod'
import type { Prisma } from '@/app/generated/prisma/client'
import { prisma } from '@/lib/prisma'
import { requireIntegrationAuth, AuthGuardError } from '@/lib/auth-guard'
import { autoTranslateOrNull } from '@/lib/translate'

export const runtime = 'nodejs'

const menuItemSchema = z.object({
  categoryExternalId: z.string().min(1),
  name: z.string().min(1),
  description: z.string(),
  price: z.number().nullable().optional(),
  imageUrl: z.string().min(1).nullable().optional(),
  location: z.string().min(1).nullable().optional(),
  category: z.string().min(1).nullable().optional(),
  extraInfo: z.string().min(1).nullable().optional(),
})

// Upsert de um item de cardápio/serviço (`ServiceItem`) vindo do PMS,
// identificado pelo `externalId` na URL. `categoryExternalId` referencia a
// categoria pelo `externalId` dela (não pelo id interno do Konekto) — a
// categoria precisa já ter sido sincronizada via
// `PUT /api/integrations/v1/menu-categories/{externalId}` antes.
export async function PUT(request: NextRequest, { params }: { params: Promise<{ externalId: string }> }) {
  const { externalId } = await params

  let hotelId: string
  try {
    ;({ hotelId } = await requireIntegrationAuth(request))
  } catch (error) {
    if (error instanceof AuthGuardError) return error.response
    throw error
  }

  const parsed = menuItemSchema.safeParse(await request.json().catch(() => null))
  if (!parsed.success) {
    return NextResponse.json({ error: 'invalid_request' }, { status: 400 })
  }
  const { categoryExternalId, name, description, price, imageUrl, location, category, extraInfo } = parsed.data

  const service = await prisma.service.findUnique({
    where: { hotelId_externalId: { hotelId, externalId: categoryExternalId } },
  })
  if (!service) {
    return NextResponse.json({ error: 'category_not_found' }, { status: 404 })
  }

  const translations = await autoTranslateOrNull({ name, description, location, category, extraInfo })
  const translationsValue = (translations ?? undefined) as Prisma.InputJsonValue | undefined

  const existing = await prisma.serviceItem.findUnique({
    where: { serviceId_externalId: { serviceId: service.id, externalId } },
  })

  if (existing) {
    const item = await prisma.serviceItem.update({
      where: { id: existing.id },
      data: {
        name,
        description,
        price,
        imageUrl,
        location,
        category,
        extraInfo,
        translations: translationsValue,
        translationsAutoGenerated: true,
      },
    })
    await prisma.hotelIntegration.update({ where: { hotelId }, data: { lastInboundSyncAt: new Date() } })
    return NextResponse.json(item)
  }

  const maxPosition = await prisma.serviceItem.aggregate({ where: { serviceId: service.id }, _max: { position: true } })
  const nextPosition = (maxPosition._max.position ?? -1) + 1

  const item = await prisma.serviceItem.create({
    data: {
      serviceId: service.id,
      externalId,
      name,
      description,
      price,
      imageUrl,
      location,
      category,
      extraInfo,
      position: nextPosition,
      translations: translationsValue,
    },
  })
  await prisma.hotelIntegration.update({ where: { hotelId }, data: { lastInboundSyncAt: new Date() } })
  return NextResponse.json(item, { status: 201 })
}
