import { NextRequest } from 'next/server'
import { beforeEach, describe, expect, it, vi } from 'vitest'

vi.mock('@/lib/prisma', () => ({
  prisma: {
    service: { findUnique: vi.fn(), update: vi.fn(), delete: vi.fn() },
  },
}))
vi.mock('@/lib/translate', () => ({ autoTranslateOrNull: vi.fn().mockResolvedValue(null) }))

import { prisma } from '@/lib/prisma'
import { signStaffToken } from '@/lib/jwt'
import { PATCH } from './route'

function patchRequest(hotelId: string, serviceId: string, token: string, body: unknown): NextRequest {
  return new NextRequest(`http://localhost/api/hotels/${hotelId}/services/${serviceId}`, {
    method: 'PATCH',
    headers: { 'content-type': 'application/json', authorization: `Bearer ${token}` },
    body: JSON.stringify(body),
  })
}

async function gerenteToken(hotelId = 'hotel_1') {
  return signStaffToken({ sub: 'staff_1', hotelId, role: 'gerente', email: 'a@b.com', name: 'A' })
}

const params = Promise.resolve({ hotelId: 'hotel_1', serviceId: 'svc_1' })

const existingWithoutOperatingHours = {
  id: 'svc_1',
  name: 'Restaurante',
  description: 'desc',
  translationsAutoGenerated: true,
  operatingDaysOfWeek: [],
  operatingStartMinute: null,
  operatingEndMinute: null,
}

describe('PATCH .../services/[serviceId] — validação de horário de funcionamento', () => {
  beforeEach(() => vi.clearAllMocks())

  it('accepts turning on a full operating-hours config in one request', async () => {
    vi.mocked(prisma.service.findUnique).mockResolvedValue(existingWithoutOperatingHours as never)
    vi.mocked(prisma.service.update).mockResolvedValue({ id: 'svc_1' } as never)
    const token = await gerenteToken()

    const response = await PATCH(
      patchRequest('hotel_1', 'svc_1', token, {
        operatingDaysOfWeek: [2, 3, 4, 5, 6, 7],
        operatingStartMinute: 1140,
        operatingEndMinute: 60,
      }),
      { params },
    )

    expect(response.status).toBe(200)
  })

  it('rejects setting operatingStartMinute alone when nothing else was ever configured', async () => {
    vi.mocked(prisma.service.findUnique).mockResolvedValue(existingWithoutOperatingHours as never)
    const token = await gerenteToken()

    const response = await PATCH(
      patchRequest('hotel_1', 'svc_1', token, { operatingStartMinute: 420 }),
      { params },
    )

    expect(response.status).toBe(400)
    expect(prisma.service.update).not.toHaveBeenCalled()
  })

  it('rejects clearing a required field while the window stays configured from before', async () => {
    const existingWithHours = {
      ...existingWithoutOperatingHours,
      operatingDaysOfWeek: [1, 2, 3, 4, 5, 6, 7],
      operatingStartMinute: 420,
      operatingEndMinute: 1380,
    }
    vi.mocked(prisma.service.findUnique).mockResolvedValue(existingWithHours as never)
    const token = await gerenteToken()

    const response = await PATCH(
      patchRequest('hotel_1', 'svc_1', token, { operatingDaysOfWeek: [] }),
      { params },
    )

    expect(response.status).toBe(400)
    expect(prisma.service.update).not.toHaveBeenCalled()
  })

  it('allows turning operating hours off by clearing all three fields together', async () => {
    // Diferente de `ServiceItem.durationMinutes` (que sozinho já liga/desliga
    // o agendamento), horário de funcionamento não tem um campo "interruptor"
    // único — os 3 campos são simétricos, então desligar precisa zerar os 3
    // juntos no mesmo PATCH.
    const existingWithHours = {
      ...existingWithoutOperatingHours,
      operatingDaysOfWeek: [1, 2, 3, 4, 5, 6, 7],
      operatingStartMinute: 420,
      operatingEndMinute: 1380,
    }
    vi.mocked(prisma.service.findUnique).mockResolvedValue(existingWithHours as never)
    vi.mocked(prisma.service.update).mockResolvedValue({ id: 'svc_1' } as never)
    const token = await gerenteToken()

    const response = await PATCH(
      patchRequest('hotel_1', 'svc_1', token, {
        operatingDaysOfWeek: [],
        operatingStartMinute: null,
        operatingEndMinute: null,
      }),
      { params },
    )

    expect(response.status).toBe(200)
  })

  it('rejects clearing operatingStartMinute alone while the other fields remain configured', async () => {
    const existingWithHours = {
      ...existingWithoutOperatingHours,
      operatingDaysOfWeek: [1, 2, 3, 4, 5, 6, 7],
      operatingStartMinute: 420,
      operatingEndMinute: 1380,
    }
    vi.mocked(prisma.service.findUnique).mockResolvedValue(existingWithHours as never)
    const token = await gerenteToken()

    const response = await PATCH(
      patchRequest('hotel_1', 'svc_1', token, { operatingStartMinute: null }),
      { params },
    )

    expect(response.status).toBe(400)
    expect(prisma.service.update).not.toHaveBeenCalled()
  })
})
