import { NextRequest } from 'next/server'
import { beforeEach, describe, expect, it, vi } from 'vitest'

vi.mock('@/lib/prisma', () => ({
  prisma: {
    serviceItem: { findFirst: vi.fn(), update: vi.fn(), delete: vi.fn() },
    partner: { findFirst: vi.fn() },
  },
}))
vi.mock('@/lib/translate', () => ({ autoTranslateOrNull: vi.fn().mockResolvedValue(null) }))

import { prisma } from '@/lib/prisma'
import { signStaffToken } from '@/lib/jwt'
import { PATCH } from './route'

function patchRequest(hotelId: string, serviceId: string, itemId: string, token: string, body: unknown): NextRequest {
  return new NextRequest(`http://localhost/api/hotels/${hotelId}/services/${serviceId}/items/${itemId}`, {
    method: 'PATCH',
    headers: { 'content-type': 'application/json', authorization: `Bearer ${token}` },
    body: JSON.stringify(body),
  })
}

async function gerenteToken(hotelId = 'hotel_1') {
  return signStaffToken({ sub: 'staff_1', hotelId, role: 'gerente', email: 'a@b.com', name: 'A' })
}

const params = Promise.resolve({ hotelId: 'hotel_1', serviceId: 'svc_1', itemId: 'item_1' })

const existingWithoutScheduling = {
  id: 'item_1',
  name: 'Massagem',
  description: 'desc',
  location: null,
  category: null,
  extraInfo: null,
  translationsAutoGenerated: true,
  durationMinutes: null,
  capacityPerSlot: null,
  availableDaysOfWeek: [],
  availabilityStartMinute: null,
  availabilityEndMinute: null,
  partnerId: null,
  paymentMode: 'hotel',
}

describe('PATCH .../items/[itemId] — validação de agendamento', () => {
  beforeEach(() => {
    vi.clearAllMocks()
  })

  it('accepts turning on a full scheduling config in one request', async () => {
    vi.mocked(prisma.serviceItem.findFirst).mockResolvedValue(existingWithoutScheduling as never)
    vi.mocked(prisma.serviceItem.update).mockResolvedValue({ id: 'item_1' } as never)
    const token = await gerenteToken()

    const response = await PATCH(
      patchRequest('hotel_1', 'svc_1', 'item_1', token, {
        durationMinutes: 60,
        capacityPerSlot: 1,
        availableDaysOfWeek: [2, 3, 4, 5, 6, 7],
        availabilityStartMinute: 840,
        availabilityEndMinute: 1380,
      }),
      { params },
    )

    expect(response.status).toBe(200)
  })

  it('rejects setting durationMinutes alone when nothing else was ever configured', async () => {
    vi.mocked(prisma.serviceItem.findFirst).mockResolvedValue(existingWithoutScheduling as never)
    const token = await gerenteToken()

    const response = await PATCH(
      patchRequest('hotel_1', 'svc_1', 'item_1', token, { durationMinutes: 60 }),
      { params },
    )

    expect(response.status).toBe(400)
    expect(prisma.serviceItem.update).not.toHaveBeenCalled()
  })

  it('rejects clearing a required field while durationMinutes stays set from before', async () => {
    const existingWithScheduling = {
      ...existingWithoutScheduling,
      durationMinutes: 60,
      capacityPerSlot: 1,
      availableDaysOfWeek: [2, 3, 4, 5, 6, 7],
      availabilityStartMinute: 840,
      availabilityEndMinute: 1380,
    }
    vi.mocked(prisma.serviceItem.findFirst).mockResolvedValue(existingWithScheduling as never)
    const token = await gerenteToken()

    // Zera a capacidade sem desligar `durationMinutes` junto — deixaria o
    // item com agendamento "ligado" mas sem capacidade configurada.
    const response = await PATCH(
      patchRequest('hotel_1', 'svc_1', 'item_1', token, { capacityPerSlot: null }),
      { params },
    )

    expect(response.status).toBe(400)
    expect(prisma.serviceItem.update).not.toHaveBeenCalled()
  })

  it('allows turning scheduling off by clearing durationMinutes alone', async () => {
    const existingWithScheduling = {
      ...existingWithoutScheduling,
      durationMinutes: 60,
      capacityPerSlot: 1,
      availableDaysOfWeek: [2, 3, 4, 5, 6, 7],
      availabilityStartMinute: 840,
      availabilityEndMinute: 1380,
    }
    vi.mocked(prisma.serviceItem.findFirst).mockResolvedValue(existingWithScheduling as never)
    vi.mocked(prisma.serviceItem.update).mockResolvedValue({ id: 'item_1' } as never)
    const token = await gerenteToken()

    const response = await PATCH(
      patchRequest('hotel_1', 'svc_1', 'item_1', token, { durationMinutes: null }),
      { params },
    )

    expect(response.status).toBe(200)
  })

  it('updates the isMinibarItem flag', async () => {
    vi.mocked(prisma.serviceItem.findFirst).mockResolvedValue(existingWithoutScheduling as never)
    vi.mocked(prisma.serviceItem.update).mockResolvedValue({ id: 'item_1', isMinibarItem: true } as never)
    const token = await gerenteToken()

    const response = await PATCH(
      patchRequest('hotel_1', 'svc_1', 'item_1', token, { isMinibarItem: true }),
      { params },
    )

    expect(response.status).toBe(200)
    expect(prisma.serviceItem.update).toHaveBeenCalledWith(
      expect.objectContaining({ data: expect.objectContaining({ isMinibarItem: true }) }),
    )
  })

  it('rejects setting paymentMode: partner while the item has no partnerId, existing or incoming', async () => {
    vi.mocked(prisma.serviceItem.findFirst).mockResolvedValue(existingWithoutScheduling as never)
    const token = await gerenteToken()

    const response = await PATCH(
      patchRequest('hotel_1', 'svc_1', 'item_1', token, { paymentMode: 'partner' }),
      { params },
    )

    expect(response.status).toBe(400)
    expect(prisma.serviceItem.update).not.toHaveBeenCalled()
  })

  it('accepts paymentMode: partner when a partnerId already exists on the item', async () => {
    const existingWithPartner = { ...existingWithoutScheduling, partnerId: 'p1', paymentMode: 'hotel' }
    vi.mocked(prisma.serviceItem.findFirst).mockResolvedValue(existingWithPartner as never)
    vi.mocked(prisma.serviceItem.update).mockResolvedValue({ id: 'item_1', paymentMode: 'partner' } as never)
    const token = await gerenteToken()

    const response = await PATCH(
      patchRequest('hotel_1', 'svc_1', 'item_1', token, { paymentMode: 'partner' }),
      { params },
    )

    expect(response.status).toBe(200)
  })

  it('rejects a partnerId that does not belong to this hotel', async () => {
    vi.mocked(prisma.serviceItem.findFirst).mockResolvedValue(existingWithoutScheduling as never)
    vi.mocked(prisma.partner.findFirst).mockResolvedValue(null)
    const token = await gerenteToken()

    const response = await PATCH(
      patchRequest('hotel_1', 'svc_1', 'item_1', token, { partnerId: 'p1' }),
      { params },
    )

    expect(response.status).toBe(400)
    expect(prisma.serviceItem.update).not.toHaveBeenCalled()
  })
})
