import { render, screen, waitFor } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { afterEach, describe, expect, it, vi } from 'vitest'
import { ServiceFormDialog } from './ServiceFormDialog'
import type { ModuleDefinition } from '@/types/moduleCatalog'

const roomServiceModule: ModuleDefinition = {
  id: 'room_service',
  name: 'Room Service',
  description: 'Pedidos de quarto.',
  category: 'hospitalidade',
  icon: 'room_service',
  placement: ['servicesMenu'],
  defaultOrder: 0,
  dependencies: [],
  implemented: true,
}

const spaModule: ModuleDefinition = {
  ...roomServiceModule,
  id: 'spa',
  name: 'Spa',
}

describe('ServiceFormDialog', () => {
  afterEach(() => vi.clearAllMocks())

  it('requires selecting a module before creating a new service', async () => {
    const onSubmitCreate = vi.fn().mockResolvedValue(undefined)
    render(
      <ServiceFormDialog
        existing={null}
        existingCategories={[]}
        allowedHospitalidadeModules={[]}
        onClose={() => {}}
        onSubmitCreate={onSubmitCreate}
        onSubmitUpdate={vi.fn()}
      />,
    )

    await userEvent.type(screen.getByLabelText('Nome do serviço'), 'Spa')
    await userEvent.type(screen.getByLabelText('Nome da nova categoria'), 'Bem-estar')
    await userEvent.click(screen.getByRole('button', { name: 'Salvar' }))

    expect(screen.getByText('Selecione o módulo deste serviço.')).toBeInTheDocument()
    expect(onSubmitCreate).not.toHaveBeenCalled()
  })

  it('includes the selected moduleId when creating a new service', async () => {
    const onSubmitCreate = vi.fn().mockResolvedValue(undefined)
    render(
      <ServiceFormDialog
        existing={null}
        existingCategories={[]}
        allowedHospitalidadeModules={[roomServiceModule, spaModule]}
        onClose={() => {}}
        onSubmitCreate={onSubmitCreate}
        onSubmitUpdate={vi.fn()}
      />,
    )

    await userEvent.type(screen.getByLabelText('Nome do serviço'), 'Spa do hotel')
    await userEvent.type(screen.getByLabelText('Nome da nova categoria'), 'Bem-estar')
    await userEvent.selectOptions(screen.getByLabelText('Módulo', { exact: false }), 'spa')
    await userEvent.click(screen.getByRole('button', { name: 'Salvar' }))

    await waitFor(() => expect(onSubmitCreate).toHaveBeenCalled())
    expect(onSubmitCreate.mock.calls[0][0]).toMatchObject({ moduleId: 'spa' })
  })

  it('shows a message instead of a picker when the hotel plan allows no Hospitalidade module', () => {
    render(
      <ServiceFormDialog
        existing={null}
        existingCategories={[]}
        allowedHospitalidadeModules={[]}
        onClose={() => {}}
        onSubmitCreate={vi.fn()}
        onSubmitUpdate={vi.fn()}
      />,
    )

    expect(screen.getByText('Nenhum módulo de Hospitalidade liberado pro plano deste hotel ainda.')).toBeInTheDocument();
    expect(screen.queryByLabelText('Módulo')).not.toBeInTheDocument()
  })

  it('does not show the module picker when editing an existing service (moduleId is fixed at creation)', () => {
    render(
      <ServiceFormDialog
        existing={{
          id: 'svc_1',
          hotelId: 'hotel_1',
          name: 'Spa',
          slug: 'spa',
          icon: 'spa',
          description: 'desc',
          type: 'activity',
          category: 'Bem-estar',
          moduleId: 'spa',
          bannerImageUrl: null,
          position: 0,
          enabled: true,
          items: [],
          translations: {},
          translationsAutoGenerated: true,
          operatingDaysOfWeek: [],
          operatingStartMinute: null,
          operatingEndMinute: null,
          tableTypes: [],
        }}
        existingCategories={['Bem-estar']}
        allowedHospitalidadeModules={[roomServiceModule, spaModule]}
        onClose={() => {}}
        onSubmitCreate={vi.fn()}
        onSubmitUpdate={vi.fn()}
      />,
    )

    expect(screen.queryByLabelText('Módulo')).not.toBeInTheDocument()
  })
})
