-- AlterTable
ALTER TABLE "services" ADD COLUMN     "translations" JSONB,
ADD COLUMN     "translationsAutoGenerated" BOOLEAN NOT NULL DEFAULT true;

-- AlterTable
ALTER TABLE "service_items" ADD COLUMN     "translations" JSONB,
ADD COLUMN     "translationsAutoGenerated" BOOLEAN NOT NULL DEFAULT true;
