/** Portado de apps/konekto_portal/lib/models/service.dart. */

/** {en: {campo: texto}, es: {campo: texto}} */
export type FieldTranslations = Record<string, Record<string, string>>

export type ServiceItemPaymentMode = 'hotel' | 'partner'

export const serviceItemPaymentModeLabel: Record<ServiceItemPaymentMode, string> = {
  hotel: 'Hotel cobra pelo Konekto',
  partner: 'Hóspede paga direto ao parceiro',
}

export interface ServiceItem {
  id: string
  name: string
  description: string
  price: number | null
  imageUrl: string | null
  location: string | null
  category: string | null
  extraInfo: string | null
  position: number
  translations: FieldTranslations
  translationsAutoGenerated: boolean
  /** null = agendamento não configurado (hóspede escolhe livremente). */
  durationMinutes: number | null
  capacityPerSlot: number | null
  /** ISO weekday (1=segunda...7=domingo). */
  availableDaysOfWeek: number[]
  availabilityStartMinute: number | null
  availabilityEndMinute: number | null
  isMinibarItem: boolean
  partnerId: string | null
  paymentMode: ServiceItemPaymentMode
}

/** Dados de criação/edição de um item — sem id/position/translations (geridos pela API). */
export interface ServiceItemInput {
  name: string
  description: string
  price: number | null
  imageUrl: string | null
  location: string | null
  category: string | null
  extraInfo: string | null
  durationMinutes: number | null
  capacityPerSlot: number | null
  availableDaysOfWeek: number[]
  availabilityStartMinute: number | null
  availabilityEndMinute: number | null
  isMinibarItem: boolean
  partnerId: string | null
  paymentMode: ServiceItemPaymentMode
}

export interface RestaurantTableType {
  id: string
  label: string | null
  seats: number
  quantity: number
}

export type ServiceType = 'room_service' | 'restaurant' | 'activity'

export const serviceTypeLabel: Record<ServiceType, string> = {
  room_service: 'Serviço de Quarto',
  restaurant: 'Restaurante',
  activity: 'Passeio / Atividade',
}

export const serviceTypeDescription: Record<ServiceType, string> = {
  room_service: 'Item por item, com quantidade e observação (ex: cardápio de quarto).',
  restaurant: 'Cardápio só informativo — a reserva é de uma mesa, não de um prato.',
  activity: 'Cada item abre um modal de dia/horário (ex: spa, eventos, passeios).',
}

export interface Service {
  id: string
  hotelId: string
  name: string
  slug: string
  icon: string
  description: string
  type: ServiceType
  category: string
  /** Módulo de Hospitalidade (Fase 12) — `null` só em serviço criado antes
   *  dessa fase e ainda não revisado; sempre presente em serviço novo. */
  moduleId: string | null
  bannerImageUrl: string | null
  position: number
  enabled: boolean
  items: ServiceItem[]
  translations: FieldTranslations
  translationsAutoGenerated: boolean
  /** Horário de funcionamento do serviço inteiro — só relevante pra room_service/restaurant. */
  operatingDaysOfWeek: number[]
  operatingStartMinute: number | null
  operatingEndMinute: number | null
  tableTypes: RestaurantTableType[]
}

export function operatingHoursApplicable(type: ServiceType): boolean {
  return type === 'room_service' || type === 'restaurant'
}
