/// Traduções de campos de texto pra inglês/espanhol — formato
/// `{en: {campo: texto}, es: {campo: texto}}`. Compartilhado por
/// [Service] e [ServiceItem].
typedef FieldTranslations = Map<String, Map<String, String>>;

FieldTranslations _parseTranslations(dynamic raw) {
  if (raw is! Map) return const {};
  final result = <String, Map<String, String>>{};
  for (final entry in raw.entries) {
    final localeMap = entry.value;
    if (localeMap is Map) {
      result[entry.key as String] = localeMap.map(
        (key, value) => MapEntry(key as String, value as String),
      );
    }
  }
  return result;
}

/// Só relevante quando o item tem um `partnerId` — decide se o valor entra
/// na conta do quarto cobrada pelo Konekto (`hotel`) ou se o hóspede paga o
/// parceiro diretamente, sem cobrança pelo Konekto (`partner`).
enum ServiceItemPaymentMode {
  hotel,
  partner;

  static ServiceItemPaymentMode fromString(String value) {
    return switch (value) {
      'hotel' => ServiceItemPaymentMode.hotel,
      'partner' => ServiceItemPaymentMode.partner,
      _ => throw ArgumentError('Modo de pagamento desconhecido: "$value"'),
    };
  }

  String get apiValue => switch (this) {
        ServiceItemPaymentMode.hotel => 'hotel',
        ServiceItemPaymentMode.partner => 'partner',
      };

  String get label => switch (this) {
        ServiceItemPaymentMode.hotel => 'Hotel cobra pelo Konekto',
        ServiceItemPaymentMode.partner => 'Hóspede paga direto ao parceiro',
      };
}

/// Item de um serviço (prato, tratamento de spa, evento, passeio, ou
/// qualquer coisa que o hotel decida oferecer). `price: null` = não é
/// "comprável" — a tela decide o que mostrar (ex: "Reservar" em vez de
/// preço) com base nisso.
///
/// `translations`/`translationsAutoGenerated`: nome/descrição/local/
/// categoria/informação extra são traduzidos automaticamente pro inglês e
/// espanhol quando o gerente salva em português (ver backend). Ficam
/// visíveis/editáveis aqui só pra permitir revisão manual no portal —
/// editar manualmente desliga a tradução automática futura desse item
/// (`translationsAutoGenerated: false`).
class ServiceItem {
  final String id;
  final String name;
  final String description;
  final double? price;
  final String? imageUrl;
  final String? location;
  final String? category;
  final String? extraInfo;
  final int position;
  final FieldTranslations translations;
  final bool translationsAutoGenerated;

  /// `null` = agendamento não configurado pra este item (hóspede escolhe
  /// qualquer dia/hora livremente). Quando setado, os outros 4 campos
  /// abaixo são obrigatórios juntos (validado no backend).
  final int? durationMinutes;
  final int? capacityPerSlot;
  /// ISO weekday (1=segunda...7=domingo).
  final List<int> availableDaysOfWeek;
  final int? availabilityStartMinute;
  final int? availabilityEndMinute;

  /// Item de frigobar/minibar — só faz sentido num serviço `roomService`.
  /// Quando `true`, o hóspede informa consumo em vez de pedir (o pedido
  /// nasce direto `completed`, sem preparo).
  final bool isMinibarItem;

  /// Empresa parceira que presta esse serviço — `null` = o próprio hotel
  /// presta.
  final String? partnerId;
  final ServiceItemPaymentMode paymentMode;

  const ServiceItem({
    required this.id,
    required this.name,
    required this.description,
    this.price,
    this.imageUrl,
    this.location,
    this.category,
    this.extraInfo,
    required this.position,
    this.translations = const {},
    this.translationsAutoGenerated = true,
    this.durationMinutes,
    this.capacityPerSlot,
    this.availableDaysOfWeek = const [],
    this.availabilityStartMinute,
    this.availabilityEndMinute,
    this.isMinibarItem = false,
    this.partnerId,
    this.paymentMode = ServiceItemPaymentMode.hotel,
  });

  factory ServiceItem.fromJson(Map<String, dynamic> json) {
    return ServiceItem(
      id: json['id'] as String,
      name: json['name'] as String,
      description: json['description'] as String,
      price: (json['price'] as num?)?.toDouble(),
      imageUrl: json['imageUrl'] as String?,
      location: json['location'] as String?,
      category: json['category'] as String?,
      extraInfo: json['extraInfo'] as String?,
      position: json['position'] as int? ?? 0,
      translations: _parseTranslations(json['translations']),
      translationsAutoGenerated:
          json['translationsAutoGenerated'] as bool? ?? true,
      durationMinutes: json['durationMinutes'] as int?,
      capacityPerSlot: json['capacityPerSlot'] as int?,
      availableDaysOfWeek:
          (json['availableDaysOfWeek'] as List<dynamic>?)
              ?.map((value) => value as int)
              .toList() ??
          const [],
      availabilityStartMinute: json['availabilityStartMinute'] as int?,
      availabilityEndMinute: json['availabilityEndMinute'] as int?,
      isMinibarItem: json['isMinibarItem'] as bool? ?? false,
      partnerId: json['partnerId'] as String?,
      paymentMode: json['paymentMode'] != null
          ? ServiceItemPaymentMode.fromString(json['paymentMode'] as String)
          : ServiceItemPaymentMode.hotel,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'name': name,
      'description': description,
      'price': price,
      'imageUrl': imageUrl,
      'location': location,
      'category': category,
      'extraInfo': extraInfo,
      'durationMinutes': durationMinutes,
      'capacityPerSlot': capacityPerSlot,
      'availableDaysOfWeek': availableDaysOfWeek,
      'availabilityStartMinute': availabilityStartMinute,
      'availabilityEndMinute': availabilityEndMinute,
      'isMinibarItem': isMinibarItem,
      'partnerId': partnerId,
      'paymentMode': paymentMode.apiValue,
    };
  }

  ServiceItem copyWith({
    String? name,
    String? description,
    double? price,
    String? imageUrl,
    String? location,
    String? category,
    String? extraInfo,
    int? durationMinutes,
    int? capacityPerSlot,
    List<int>? availableDaysOfWeek,
    int? availabilityStartMinute,
    int? availabilityEndMinute,
    bool? isMinibarItem,
    String? partnerId,
    ServiceItemPaymentMode? paymentMode,
  }) {
    return ServiceItem(
      id: id,
      name: name ?? this.name,
      description: description ?? this.description,
      price: price ?? this.price,
      imageUrl: imageUrl ?? this.imageUrl,
      location: location ?? this.location,
      category: category ?? this.category,
      extraInfo: extraInfo ?? this.extraInfo,
      position: position,
      translations: translations,
      translationsAutoGenerated: translationsAutoGenerated,
      durationMinutes: durationMinutes ?? this.durationMinutes,
      capacityPerSlot: capacityPerSlot ?? this.capacityPerSlot,
      availableDaysOfWeek: availableDaysOfWeek ?? this.availableDaysOfWeek,
      availabilityStartMinute:
          availabilityStartMinute ?? this.availabilityStartMinute,
      availabilityEndMinute:
          availabilityEndMinute ?? this.availabilityEndMinute,
      isMinibarItem: isMinibarItem ?? this.isMinibarItem,
      partnerId: partnerId ?? this.partnerId,
      paymentMode: paymentMode ?? this.paymentMode,
    );
  }
}

/// Um "tipo" de mesa de um restaurante (ex: "10 mesas de 4 lugares") — não
/// uma mesa física individual, já que o hóspede reserva por tamanho, não
/// por mesa específica.
class RestaurantTableType {
  final String id;
  final String? label;
  final int seats;
  final int quantity;

  const RestaurantTableType({
    required this.id,
    this.label,
    required this.seats,
    required this.quantity,
  });

  factory RestaurantTableType.fromJson(Map<String, dynamic> json) {
    return RestaurantTableType(
      id: json['id'] as String,
      label: json['label'] as String?,
      seats: json['seats'] as int,
      quantity: json['quantity'] as int,
    );
  }
}

/// Decide o comportamento do serviço no app do hóspede:
/// - `roomService`: cardápio pedido item a item (quantidade + observação).
/// - `restaurant`: cardápio só informativo; reserva é da MESA como um todo
///   (um botão único abaixo da lista), não por prato.
/// - `activity`: qualquer experiência agendável item a item (spa, eventos,
///   passeios, ou algo novo) — cada item abre o modal de dia/hora.
enum ServiceType {
  roomService,
  restaurant,
  activity;

  static ServiceType fromString(String value) {
    return switch (value) {
      'room_service' => ServiceType.roomService,
      'restaurant' => ServiceType.restaurant,
      'activity' => ServiceType.activity,
      _ => throw ArgumentError('Tipo de serviço desconhecido: "$value"'),
    };
  }

  String get apiValue => switch (this) {
    ServiceType.roomService => 'room_service',
    ServiceType.restaurant => 'restaurant',
    ServiceType.activity => 'activity',
  };

  String get label => switch (this) {
    ServiceType.roomService => 'Serviço de Quarto',
    ServiceType.restaurant => 'Restaurante',
    ServiceType.activity => 'Passeio / Atividade',
  };
}

/// Serviço criado pelo hotel (Room Service, Spa, um restaurante específico,
/// ou algo totalmente novo) — o hotel define nome/ícone/descrição, sem
/// tipos fixos no código.
///
/// `type` decide o COMPORTAMENTO no app do hóspede — só 3 valores
/// possíveis, definido na criação, sem edição depois (mesmo padrão do
/// `slug`).
///
/// `category` é o rótulo livre que agrupa o serviço na lista do portal
/// (ex: "Restaurante", "Lavanderia", "Transfer") — o hotel cria quantas
/// quiser; cada categoria nova escolhe um dos 3 `type` por trás. Diferente
/// de `type`, pode ser editada depois (é só organização visual).
class Service {
  final String id;
  final String hotelId;
  final String name;
  final String slug;
  final String icon;
  final String description;
  final ServiceType type;
  final String category;
  final String? bannerImageUrl;
  final int position;
  final bool enabled;
  final List<ServiceItem> items;
  final FieldTranslations translations;
  final bool translationsAutoGenerated;

  /// Horário de funcionamento do SERVIÇO inteiro — não confundir com a
  /// janela por item (`ServiceItem`, só usada por `activity`). `null`/`[]`
  /// = sem restrição. Só relevante pra `roomService`/`restaurant`.
  final List<int> operatingDaysOfWeek;
  final int? operatingStartMinute;
  final int? operatingEndMinute;
  final List<RestaurantTableType> tableTypes;

  const Service({
    required this.id,
    required this.hotelId,
    required this.name,
    required this.slug,
    required this.icon,
    required this.description,
    required this.type,
    required this.category,
    this.bannerImageUrl,
    required this.position,
    required this.enabled,
    this.items = const [],
    this.translations = const {},
    this.translationsAutoGenerated = true,
    this.operatingDaysOfWeek = const [],
    this.operatingStartMinute,
    this.operatingEndMinute,
    this.tableTypes = const [],
  });

  factory Service.fromJson(Map<String, dynamic> json) {
    final rawItems = json['items'] as List<dynamic>?;
    final rawTableTypes = json['tableTypes'] as List<dynamic>?;
    return Service(
      id: json['id'] as String,
      hotelId: json['hotelId'] as String,
      name: json['name'] as String,
      slug: json['slug'] as String,
      icon: json['icon'] as String,
      description: json['description'] as String,
      type: ServiceType.fromString(json['type'] as String),
      category: json['category'] as String,
      bannerImageUrl: json['bannerImageUrl'] as String?,
      position: json['position'] as int? ?? 0,
      enabled: json['enabled'] as bool? ?? true,
      items: rawItems == null
          ? const []
          : rawItems
                .map((raw) => ServiceItem.fromJson(raw as Map<String, dynamic>))
                .toList(),
      translations: _parseTranslations(json['translations']),
      translationsAutoGenerated:
          json['translationsAutoGenerated'] as bool? ?? true,
      operatingDaysOfWeek:
          (json['operatingDaysOfWeek'] as List<dynamic>?)
              ?.map((value) => value as int)
              .toList() ??
          const [],
      operatingStartMinute: json['operatingStartMinute'] as int?,
      operatingEndMinute: json['operatingEndMinute'] as int?,
      tableTypes: rawTableTypes == null
          ? const []
          : rawTableTypes
                .map(
                  (raw) =>
                      RestaurantTableType.fromJson(raw as Map<String, dynamic>),
                )
                .toList(),
    );
  }
}
