import { NextRequest, NextResponse } from 'next/server'
import { z } from 'zod'
import type { Prisma } from '@/app/generated/prisma/client'
import { prisma } from '@/lib/prisma'
import { requireIntegrationAuth, AuthGuardError } from '@/lib/auth-guard'
import { autoTranslateOrNull } from '@/lib/translate'
import { slugify } from '@/lib/slugify'

export const runtime = 'nodejs'

const menuCategorySchema = z.object({
  name: z.string().min(1),
  icon: z.string().min(1),
  description: z.string(),
  type: z.enum(['room_service', 'restaurant', 'activity']),
  category: z.string().trim().min(1),
  bannerImageUrl: z.string().min(1).nullable().optional(),
  enabled: z.boolean().optional(),
})

// Upsert de uma categoria de cardápio/serviço (`Service`) vinda do PMS,
// identificada pelo `externalId` na URL. `slug` é derivado de `name` na
// criação (mesma lógica do formulário manual do portal,
// `services_list_page.dart:_slugify`) e nunca muda depois — mesma regra de
// imutabilidade que já vale pra criação manual. `type` também só é
// aplicado na criação (comportamento do serviço não muda depois de criado).
export async function PUT(request: NextRequest, { params }: { params: Promise<{ externalId: string }> }) {
  const { externalId } = await params

  let hotelId: string
  try {
    ;({ hotelId } = await requireIntegrationAuth(request))
  } catch (error) {
    if (error instanceof AuthGuardError) return error.response
    throw error
  }

  const parsed = menuCategorySchema.safeParse(await request.json().catch(() => null))
  if (!parsed.success) {
    return NextResponse.json({ error: 'invalid_request' }, { status: 400 })
  }
  const { name, icon, description, type, category, bannerImageUrl, enabled } = parsed.data

  const existing = await prisma.service.findUnique({ where: { hotelId_externalId: { hotelId, externalId } } })

  const translations = await autoTranslateOrNull({ name, description })
  const translationsValue = (translations ?? undefined) as Prisma.InputJsonValue | undefined

  if (existing) {
    const service = await prisma.service.update({
      where: { id: existing.id },
      data: {
        name,
        icon,
        description,
        category,
        bannerImageUrl,
        enabled: enabled ?? existing.enabled,
        translations: translationsValue,
        translationsAutoGenerated: true,
      },
    })
    await prisma.hotelIntegration.update({ where: { hotelId }, data: { lastInboundSyncAt: new Date() } })
    return NextResponse.json(service)
  }

  const slug = slugify(name) || externalId
  const slugTaken = await prisma.service.findUnique({ where: { hotelId_slug: { hotelId, slug } } })
  if (slugTaken) {
    return NextResponse.json({ error: 'slug_already_exists' }, { status: 409 })
  }

  const maxPosition = await prisma.service.aggregate({ where: { hotelId }, _max: { position: true } })
  const nextPosition = (maxPosition._max.position ?? -1) + 1

  const service = await prisma.service.create({
    data: {
      hotelId,
      externalId,
      name,
      slug,
      icon,
      description,
      type,
      category,
      bannerImageUrl,
      enabled: enabled ?? true,
      position: nextPosition,
      translations: translationsValue,
    },
  })
  await prisma.hotelIntegration.update({ where: { hotelId }, data: { lastInboundSyncAt: new Date() } })
  return NextResponse.json(service, { status: 201 })
}
