import 'dart:convert';
import 'package:http/http.dart' as http;
import 'package:konekto_portal/api_config.dart';
import 'package:konekto_portal/models/service.dart';

/// Lê e gerencia os serviços dinâmicos de um hotel (`Service`/`ServiceItem`
/// na API) — substitui o `CatalogRepository` específico de Room Service da
/// Fase 3 por um repositório genérico que serve qualquer serviço que o
/// hotel crie.
class ServiceRepository {
  final http.Client _client;

  ServiceRepository({http.Client? client}) : _client = client ?? http.Client();

  Future<List<Service>> listServices(String hotelId) async {
    final response = await _client.get(
      Uri.parse('$apiBaseUrl/api/hotels/$hotelId/services'),
    );
    if (response.statusCode != 200) {
      throw StateError(
        'Falha ao carregar serviços (status ${response.statusCode}).',
      );
    }
    final raw = jsonDecode(response.body) as List<dynamic>;
    return raw
        .map((item) => Service.fromJson(item as Map<String, dynamic>))
        .toList();
  }

  Future<Service> getService(String hotelId, String serviceId) async {
    final response = await _client.get(
      Uri.parse('$apiBaseUrl/api/hotels/$hotelId/services/$serviceId'),
    );
    if (response.statusCode != 200) {
      throw StateError(
        'Falha ao carregar serviço (status ${response.statusCode}).',
      );
    }
    return Service.fromJson(jsonDecode(response.body) as Map<String, dynamic>);
  }

  Future<Service> createService({
    required String hotelId,
    required String token,
    required String name,
    required String slug,
    required String icon,
    required String description,
    required ServiceType type,
    required String category,
    List<int>? operatingDaysOfWeek,
    int? operatingStartMinute,
    int? operatingEndMinute,
  }) async {
    final response = await _client.post(
      Uri.parse('$apiBaseUrl/api/hotels/$hotelId/services'),
      headers: {
        'Content-Type': 'application/json',
        'Authorization': 'Bearer $token',
      },
      body: jsonEncode({
        'name': name,
        'slug': slug,
        'icon': icon,
        'description': description,
        'type': type.apiValue,
        'category': category,
        if (operatingDaysOfWeek != null)
          'operatingDaysOfWeek': operatingDaysOfWeek,
        if (operatingStartMinute != null)
          'operatingStartMinute': operatingStartMinute,
        if (operatingEndMinute != null)
          'operatingEndMinute': operatingEndMinute,
      }),
    );
    if (response.statusCode != 201) {
      throw StateError(
        'Falha ao criar serviço (status ${response.statusCode}).',
      );
    }
    return Service.fromJson(jsonDecode(response.body) as Map<String, dynamic>);
  }

  /// `manualTranslations`, quando informado, marca as traduções como uma
  /// edição manual da equipe do hotel — o backend desliga a tradução
  /// automática futura desse serviço (ver `translationsAutoGenerated`).
  /// Só deve ser enviado quando a equipe de fato editou a seção de
  /// traduções no portal, nunca em toda edição (senão qualquer troca de
  /// nome/ícone desligaria a tradução automática sem querer).
  /// `includeOperatingHours: true` manda os 3 campos de horário sempre
  /// juntos (mesmo que `null`/vazio) — diferente dos outros campos
  /// (omitidos quando `null` = "não mexer"), horário de funcionamento não
  /// tem um campo "interruptor" único, então desligar precisa zerar os 3
  /// no mesmo PATCH (ver `validateOperatingHoursFields` no backend).
  Future<void> updateService({
    required String hotelId,
    required String serviceId,
    required String token,
    String? name,
    String? icon,
    String? description,
    String? category,
    bool? enabled,
    FieldTranslations? manualTranslations,
    bool includeOperatingHours = false,
    List<int>? operatingDaysOfWeek,
    int? operatingStartMinute,
    int? operatingEndMinute,
  }) async {
    final response = await _client.patch(
      Uri.parse('$apiBaseUrl/api/hotels/$hotelId/services/$serviceId'),
      headers: {
        'Content-Type': 'application/json',
        'Authorization': 'Bearer $token',
      },
      body: jsonEncode({
        if (name != null) 'name': name,
        if (icon != null) 'icon': icon,
        if (description != null) 'description': description,
        if (category != null) 'category': category,
        if (enabled != null) 'enabled': enabled,
        if (manualTranslations != null) 'translations': manualTranslations,
        if (includeOperatingHours) ...{
          'operatingDaysOfWeek': operatingDaysOfWeek ?? const [],
          'operatingStartMinute': operatingStartMinute,
          'operatingEndMinute': operatingEndMinute,
        },
      }),
    );
    if (response.statusCode != 200) {
      throw StateError(
        'Falha ao atualizar serviço (status ${response.statusCode}).',
      );
    }
  }

  /// PATCH mínimo só de `position` — usado ao arrastar pra reordenar
  /// serviços no portal, separado de [updateService] pra não precisar
  /// mandar os outros campos (nome, ícone, etc.) só pra mover um card.
  Future<void> updateServicePosition({
    required String hotelId,
    required String serviceId,
    required String token,
    required int position,
  }) async {
    final response = await _client.patch(
      Uri.parse('$apiBaseUrl/api/hotels/$hotelId/services/$serviceId'),
      headers: {
        'Content-Type': 'application/json',
        'Authorization': 'Bearer $token',
      },
      body: jsonEncode({'position': position}),
    );
    if (response.statusCode != 200) {
      throw StateError(
        'Falha ao reordenar serviço (status ${response.statusCode}).',
      );
    }
  }

  Future<void> deleteService({
    required String hotelId,
    required String serviceId,
    required String token,
  }) async {
    final response = await _client.delete(
      Uri.parse('$apiBaseUrl/api/hotels/$hotelId/services/$serviceId'),
      headers: {'Authorization': 'Bearer $token'},
    );
    if (response.statusCode != 200) {
      throw StateError(
        'Falha ao remover serviço (status ${response.statusCode}).',
      );
    }
  }

  Future<ServiceItem> createItem({
    required String hotelId,
    required String serviceId,
    required String token,
    required ServiceItem item,
  }) async {
    final response = await _client.post(
      Uri.parse('$apiBaseUrl/api/hotels/$hotelId/services/$serviceId/items'),
      headers: {
        'Content-Type': 'application/json',
        'Authorization': 'Bearer $token',
      },
      body: jsonEncode(item.toJson()),
    );
    if (response.statusCode != 201) {
      throw StateError('Falha ao criar item (status ${response.statusCode}).');
    }
    return ServiceItem.fromJson(
      jsonDecode(response.body) as Map<String, dynamic>,
    );
  }

  /// `manualTranslations`, quando informado, marca as traduções como uma
  /// edição manual da equipe do hotel (mesma regra de [updateService]) —
  /// só deve ser enviado quando a seção de traduções foi de fato editada.
  Future<ServiceItem> updateItem({
    required String hotelId,
    required String serviceId,
    required String itemId,
    required String token,
    required ServiceItem item,
    FieldTranslations? manualTranslations,
  }) async {
    final body = item.toJson();
    if (manualTranslations != null) body['translations'] = manualTranslations;
    final response = await _client.patch(
      Uri.parse(
        '$apiBaseUrl/api/hotels/$hotelId/services/$serviceId/items/$itemId',
      ),
      headers: {
        'Content-Type': 'application/json',
        'Authorization': 'Bearer $token',
      },
      body: jsonEncode(body),
    );
    if (response.statusCode != 200) {
      throw StateError(
        'Falha ao atualizar item (status ${response.statusCode}).',
      );
    }
    return ServiceItem.fromJson(
      jsonDecode(response.body) as Map<String, dynamic>,
    );
  }

  /// PATCH mínimo só de `position` — mesmo racional de
  /// [updateServicePosition], pro drag-and-drop de itens dentro de um
  /// serviço.
  Future<void> updateItemPosition({
    required String hotelId,
    required String serviceId,
    required String itemId,
    required String token,
    required int position,
  }) async {
    final response = await _client.patch(
      Uri.parse(
        '$apiBaseUrl/api/hotels/$hotelId/services/$serviceId/items/$itemId',
      ),
      headers: {
        'Content-Type': 'application/json',
        'Authorization': 'Bearer $token',
      },
      body: jsonEncode({'position': position}),
    );
    if (response.statusCode != 200) {
      throw StateError(
        'Falha ao reordenar item (status ${response.statusCode}).',
      );
    }
  }

  Future<void> deleteItem({
    required String hotelId,
    required String serviceId,
    required String itemId,
    required String token,
  }) async {
    final response = await _client.delete(
      Uri.parse(
        '$apiBaseUrl/api/hotels/$hotelId/services/$serviceId/items/$itemId',
      ),
      headers: {'Authorization': 'Bearer $token'},
    );
    if (response.statusCode != 200) {
      throw StateError(
        'Falha ao remover item (status ${response.statusCode}).',
      );
    }
  }

  Future<List<RestaurantTableType>> listTableTypes(
    String hotelId,
    String serviceId,
  ) async {
    final response = await _client.get(
      Uri.parse(
        '$apiBaseUrl/api/hotels/$hotelId/services/$serviceId/table-types',
      ),
    );
    if (response.statusCode != 200) {
      throw StateError(
        'Falha ao carregar tipos de mesa (status ${response.statusCode}).',
      );
    }
    final raw = jsonDecode(response.body) as List<dynamic>;
    return raw
        .map(
          (item) =>
              RestaurantTableType.fromJson(item as Map<String, dynamic>),
        )
        .toList();
  }

  Future<RestaurantTableType> createTableType({
    required String hotelId,
    required String serviceId,
    required String token,
    String? label,
    required int seats,
    required int quantity,
  }) async {
    final response = await _client.post(
      Uri.parse(
        '$apiBaseUrl/api/hotels/$hotelId/services/$serviceId/table-types',
      ),
      headers: {
        'Content-Type': 'application/json',
        'Authorization': 'Bearer $token',
      },
      body: jsonEncode({'label': label, 'seats': seats, 'quantity': quantity}),
    );
    if (response.statusCode != 201) {
      throw StateError(
        'Falha ao criar tipo de mesa (status ${response.statusCode}).',
      );
    }
    return RestaurantTableType.fromJson(
      jsonDecode(response.body) as Map<String, dynamic>,
    );
  }

  Future<RestaurantTableType> updateTableType({
    required String hotelId,
    required String serviceId,
    required String tableTypeId,
    required String token,
    String? label,
    int? seats,
    int? quantity,
  }) async {
    final response = await _client.patch(
      Uri.parse(
        '$apiBaseUrl/api/hotels/$hotelId/services/$serviceId/table-types/$tableTypeId',
      ),
      headers: {
        'Content-Type': 'application/json',
        'Authorization': 'Bearer $token',
      },
      body: jsonEncode({
        'label': label,
        if (seats != null) 'seats': seats,
        if (quantity != null) 'quantity': quantity,
      }),
    );
    if (response.statusCode != 200) {
      throw StateError(
        'Falha ao atualizar tipo de mesa (status ${response.statusCode}).',
      );
    }
    return RestaurantTableType.fromJson(
      jsonDecode(response.body) as Map<String, dynamic>,
    );
  }

  Future<void> deleteTableType({
    required String hotelId,
    required String serviceId,
    required String tableTypeId,
    required String token,
  }) async {
    final response = await _client.delete(
      Uri.parse(
        '$apiBaseUrl/api/hotels/$hotelId/services/$serviceId/table-types/$tableTypeId',
      ),
      headers: {'Authorization': 'Bearer $token'},
    );
    if (response.statusCode != 200) {
      throw StateError(
        'Falha ao remover tipo de mesa (status ${response.statusCode}).',
      );
    }
  }
}
