export type PublicFeatureStatus = "available" | "in-development" | "coming-soon"

export type Audience = "hotel" | "guest" | "partner" | "network" | "enterprise"

export interface PublicFeature {
  id: string
  displayName: string
  category: string
  status: PublicFeatureStatus
  audience: Audience[]
  planAvailability?: ("essential" | "premium" | "enterprise")[]
  description: string
}

export const STATUS_LABEL: Record<PublicFeatureStatus, string> = {
  available: "Disponível",
  "in-development": "Em desenvolvimento",
  "coming-soon": "Em breve",
}

export const PUBLIC_FEATURES: PublicFeature[] = [
  {
    id: "stay-info",
    displayName: "Informações da hospedagem",
    category: "Experiência da estadia",
    status: "available",
    audience: ["guest", "hotel"],
    planAvailability: ["essential", "premium", "enterprise"],
    description: "Dados da estadia, quarto, orientações e informações essenciais do hóspede.",
  },
  {
    id: "wifi-orientation",
    displayName: "Wi-Fi e orientações",
    category: "Experiência da estadia",
    status: "available",
    audience: ["guest", "hotel"],
    planAvailability: ["essential", "premium", "enterprise"],
    description: "Acesso rápido a rede, credenciais e orientações práticas durante a estadia.",
  },
  {
    id: "guest-profile",
    displayName: "Perfil do hóspede",
    category: "Experiência da estadia",
    status: "available",
    audience: ["guest"],
    planAvailability: ["essential", "premium", "enterprise"],
    description: "Área pessoal do hóspede dentro da jornada digital da hospedagem.",
  },
  {
    id: "bookings-orders",
    displayName: "Pedidos e reservas",
    category: "Experiência da estadia",
    status: "available",
    audience: ["guest", "hotel"],
    planAvailability: ["essential", "premium", "enterprise"],
    description: "Fluxo para acompanhar pedidos, reservas e interações operacionais da estadia.",
  },
  {
    id: "guest-messages",
    displayName: "Mensagens com a equipe",
    category: "Experiência da estadia",
    status: "available",
    audience: ["guest", "hotel"],
    planAvailability: ["essential", "premium", "enterprise"],
    description: "Comunicação direta entre hóspede e equipe do hotel em um fluxo centralizado.",
  },
  {
    id: "basic-notices",
    displayName: "Avisos e notificações básicas",
    category: "Experiência da estadia",
    status: "available",
    audience: ["guest", "hotel"],
    planAvailability: ["essential", "premium", "enterprise"],
    description: "Avisos operacionais e atualizações relevantes durante a jornada do hóspede.",
  },
  {
    id: "room-service",
    displayName: "Room Service",
    category: "Serviços do hotel",
    status: "available",
    audience: ["guest", "hotel"],
    planAvailability: ["essential", "premium", "enterprise"],
    description: "Pedidos de quarto operados dentro da plataforma.",
  },
  {
    id: "restaurants",
    displayName: "Restaurantes",
    category: "Serviços do hotel",
    status: "available",
    audience: ["guest", "hotel"],
    planAvailability: ["essential", "premium", "enterprise"],
    description: "Cardápios, reservas e experiências gastronômicas do hotel.",
  },
  {
    id: "tours",
    displayName: "Passeios",
    category: "Serviços do hotel",
    status: "available",
    audience: ["guest", "hotel"],
    planAvailability: ["essential", "premium", "enterprise"],
    description: "Experiências, passeios e atividades configuradas na operação do hotel, válidas para uso controlado dentro do piloto atual.",
  },
  {
    id: "spa",
    displayName: "Spa",
    category: "Serviços do hotel",
    status: "available",
    audience: ["guest", "hotel"],
    planAvailability: ["premium", "enterprise"],
    description: "Tratamentos e ofertas de bem-estar dentro da jornada do hóspede, em uso controlado no escopo atual do piloto.",
  },
  {
    id: "promotions",
    displayName: "Promoções e benefícios",
    category: "Relacionamento e receita",
    status: "available",
    audience: ["guest", "hotel"],
    planAvailability: ["premium", "enterprise"],
    description: "Campanhas e benefícios ativados no contexto da hospedagem, com uso controlado na fase atual do piloto.",
  },
  {
    id: "loyalty",
    displayName: "Programa de fidelidade",
    category: "Relacionamento e receita",
    status: "in-development",
    audience: ["guest", "hotel"],
    planAvailability: ["premium", "enterprise"],
    description: "Base de fidelização e benefícios para retorno do hóspede.",
  },
  {
    id: "wallet",
    displayName: "Carteira da hospedagem",
    category: "Relacionamento e receita",
    status: "in-development",
    audience: ["guest", "hotel"],
    planAvailability: ["premium", "enterprise"],
    description: "Estrutura para consolidar consumo, benefícios e evolução da jornada financeira.",
  },
  {
    id: "digital-checkin",
    displayName: "Check-in digital",
    category: "Jornada digital",
    status: "in-development",
    audience: ["guest", "hotel"],
    planAvailability: ["premium", "enterprise"],
    description: "Próxima evolução da chegada do hóspede com menos atrito e mais autonomia.",
  },
  {
    id: "digital-checkout",
    displayName: "Check-out digital",
    category: "Jornada digital",
    status: "in-development",
    audience: ["guest", "hotel"],
    planAvailability: ["premium", "enterprise"],
    description: "Encerramento de estadia mais simples, conectado e menos dependente da recepção.",
  },
  {
    id: "interactive-map",
    displayName: "Mapa interativo",
    category: "Jornada digital",
    status: "coming-soon",
    audience: ["guest"],
    planAvailability: ["premium", "enterprise"],
    description: "Navegação visual por áreas, serviços e pontos importantes do hotel.",
  },
  {
    id: "smart-notifications",
    displayName: "Notificações inteligentes",
    category: "Jornada digital",
    status: "coming-soon",
    audience: ["guest", "hotel"],
    planAvailability: ["premium", "enterprise"],
    description: "Mensagens contextuais baseadas em momento da estadia, ofertas e operação.",
  },
  {
    id: "multilingual-chat",
    displayName: "Chat multilíngue",
    category: "Jornada digital",
    status: "coming-soon",
    audience: ["guest", "hotel"],
    planAvailability: ["enterprise"],
    description: "Comunicação mais fluida entre hotel e hóspedes de diferentes idiomas.",
  },
  {
    id: "concierge",
    displayName: "Concierge",
    category: "Serviços do hotel",
    status: "coming-soon",
    audience: ["guest", "hotel"],
    planAvailability: ["premium", "enterprise"],
    description: "Atendimento de concierge como camada premium da experiência da hospedagem.",
  },
  {
    id: "events",
    displayName: "Eventos",
    category: "Serviços do hotel",
    status: "coming-soon",
    audience: ["guest", "hotel"],
    planAvailability: ["premium", "enterprise"],
    description: "Programação, ativações e experiências especiais do hotel.",
  },
  {
    id: "laundry",
    displayName: "Lavanderia",
    category: "Serviços do hotel",
    status: "coming-soon",
    audience: ["guest", "hotel"],
    planAvailability: ["premium", "enterprise"],
    description: "Serviço adicional integrado à operação e à jornada do hóspede.",
  },
  {
    id: "transport",
    displayName: "Transporte e transfer",
    category: "Serviços do hotel",
    status: "coming-soon",
    audience: ["guest", "hotel", "partner"],
    planAvailability: ["premium", "enterprise"],
    description: "Solicitações e experiências de mobilidade integradas à hospedagem.",
  },
  {
    id: "partner-network",
    displayName: "Rede Sevvn",
    category: "Rede e experiências",
    status: "in-development",
    audience: ["hotel", "partner", "network", "enterprise"],
    planAvailability: ["premium", "enterprise"],
    description: "Camada em evolução que conecta hotéis, parceiros locais e novas experiências durante a estadia.",
  },
  {
    id: "partner-offers",
    displayName: "Ofertas e experiências parceiras",
    category: "Rede e experiências",
    status: "coming-soon",
    audience: ["guest", "partner", "hotel"],
    planAvailability: ["premium", "enterprise"],
    description: "Distribuição de experiências, benefícios e oportunidades fora da operação própria do hotel.",
  },
  {
    id: "partner-analytics",
    displayName: "Analytics para parceiros",
    category: "Rede e experiências",
    status: "coming-soon",
    audience: ["partner", "network", "enterprise"],
    planAvailability: ["enterprise"],
    description: "Camada futura de visibilidade e performance para a rede de parceiros da Sevvn.",
  },
]

export function getFeaturesByStatus(status: PublicFeatureStatus): PublicFeature[] {
  return PUBLIC_FEATURES.filter((feature) => feature.status === status)
}
